"use client";
import React, { createContext, useContext, useState } from "react";

export type Language = "en" | "hi" | "bn" | "te" | "mr" | "ta";

export const languageNames: Record<Language, string> = {
  "en": "English",
  "hi": "Hindi",
  "bn": "Bengali",
  "te": "Telugu",
  "mr": "Marathi",
  "ta": "Tamil"
};

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  "en": {
    "home": "Home",
    "dashboard": "Live Data",
    "privacy": "Privacy & Truth",
    "begin_enrollment": "Begin Self-Enrolment",
    "hero_title": "Census 2027: Our Nation in Focus",
    "hero_subtitle": "Every data point represents a person, a family, and a future.",
    "story_map": "National Story Map",
    "live_sync": "Live Sync",
    "click_here": "Self-Enrolment - Click Here",
    "total_enumerated": "Total Enumerated",
    "citizens_recorded": "Citizens successfully recorded",
    "target_completion": "Target Completion",
    "active_workers": "Active Field Workers",
    "deployed": "85% deployed",
    "enum_title": "Self-Enrolment Portal",
    "tap_hear": "Tap to Hear Instructions",
    "listening": "Listening... Speak Now",
    "personal_details": "Personal Details",
    "full_name": "What is your Full Name?",
    "dob": "Date of Birth",
    "household_details": "Household Details",
    "address": "Where do you live?",
    "members": "How many people live here?",
    "review_submit": "Review & Submit",
    "back": "Back",
    "continue": "Continue",
    "submit": "Submit Securely",
    "name": "Name",
    "total_members": "Total Members",
    "speech_welcome": "Hello! I am your voice guide. Let's start with your Personal Information.",
    "speech_name": "What is your full name? You can tap the microphone to speak.",
    "speech_address": "Where do you live? Tap the mic to say your address.",
    "speech_back": "Going back one step.",
    "speech_next": "Perfect, let's move to the next step.",
    "speech_submitted": "You are all done! Your data has been securely submitted.",
    "success_title": "Enrolment Successful!",
    "success_message": "Thank you for participating in Census 2027.",
    "go_dashboard": "View Live Data Dashboard",
    "gender": "Gender",
    "select_gender": "Select Gender",
    "male": "Male",
    "female": "Female",
    "transgender": "Transgender / Other",
    "religion": "Religion",
    "select_religion": "Select Religion",
    "hinduism": "Hinduism",
    "islam": "Islam",
    "christianity": "Christianity",
    "sikhism": "Sikhism",
    "buddhism": "Buddhism",
    "jainism": "Jainism",
    "other": "Other",
    "literacy": "Literacy Status",
    "select_literacy": "Select Status",
    "literate": "Literate",
    "illiterate": "Illiterate",
    "state": "State",
    "district": "District",
    "city_town": "City / Town",
    "select_state": "Select State",
    "select_district": "Select District",
    "select_city": "Select City / Town",
    "enrollment_date": "Enrolment Date"
  },
  "hi": {
    "home": "होम",
    "dashboard": "लाइव डेटा",
    "privacy": "गोपनीयता और सत्य",
    "begin_enrollment": "नामांकन शुरू करें",
    "hero_title": "जनगणना 2027: हमारा राष्ट्र ध्यान में",
    "hero_subtitle": "हर डेटा बिंदु एक व्यक्ति, एक परिवार और भविष्य का प्रतिनिधित्व करता है।",
    "story_map": "राष्ट्रीय कहानी मानचित्र",
    "live_sync": "लाइव सिंक",
    "click_here": "स्व-गणना - यहां क्लिक करें",
    "total_enumerated": "कुल गणना",
    "citizens_recorded": "नागरिक सफलतापूर्वक रिकॉर्ड किए गए",
    "target_completion": "लक्ष्य पूर्णता",
    "active_workers": "सक्रिय फील्ड कार्यकर्ता",
    "deployed": "85% तैनात",
    "enum_title": "स्व-गणना पोर्टल",
    "tap_hear": "निर्देश सुनने के लिए टैप करें",
    "listening": "सुन रहा हूँ... अब बोलें",
    "personal_details": "व्यक्तिगत विवरण",
    "full_name": "आपका पूरा नाम क्या है?",
    "dob": "जन्म तिथि",
    "household_details": "घरेलू विवरण",
    "address": "आप कहाँ रहते हैं?",
    "members": "यहाँ कितने लोग रहते हैं?",
    "review_submit": "समीक्षा और जमा करें",
    "back": "पीछे",
    "continue": "जारी रखें",
    "submit": "सुरक्षित रूप से जमा करें",
    "name": "नाम",
    "total_members": "कुल सदस्य",
    "speech_welcome": "नमस्ते! मैं आपका वॉयस गाइड हूं। चलिए आपकी व्यक्तिगत जानकारी से शुरू करते हैं।",
    "speech_name": "आपका पूरा नाम क्या है? बोलने के लिए आप माइक्रोफ़ोन टैप कर सकते हैं।",
    "speech_address": "आप कहाँ रहते हैं? अपना पता बताने के लिए माइक टैप करें।",
    "speech_back": "एक कदम पीछे जा रहे हैं।",
    "speech_next": "बिल्कुल सही, चलिए अगले कदम पर चलते हैं।",
    "speech_submitted": "आपका काम हो गया! आपका डेटा सुरक्षित रूप से जमा कर दिया गया है।",
    "success_title": "नामांकन सफल!",
    "success_message": "जनगणना 2027 में भाग लेने के लिए धन्यवाद।",
    "go_dashboard": "लाइव डेटा डैशबोर्ड देखें",
    "gender": "लिंग",
    "select_gender": "लिंग चुनें",
    "male": "पुरुष",
    "female": "महिला",
    "transgender": "ट्रांसजेंडर / अन्य",
    "religion": "धर्म",
    "select_religion": "धर्म चुनें",
    "hinduism": "हिन्दू धर्म",
    "islam": "इस्लाम",
    "christianity": "ईसाई धर्म",
    "sikhism": "सिख धर्म",
    "buddhism": "बौद्ध धर्म",
    "jainism": "जैन धर्म",
    "other": "अन्य",
    "literacy": "साक्षरता स्थिति",
    "select_literacy": "स्थिति चुनें",
    "literate": "साक्षर",
    "illiterate": "निरक्षर",
    "state": "राज्य",
    "district": "ज़िला",
    "city_town": "शहर / कस्बा",
    "select_state": "राज्य चुनें",
    "select_district": "ज़िला चुनें",
    "select_city": "शहर चुनें",
    "enrollment_date": "नामांकन तिथि"
  },
  "bn": {
    "home": "হোম",
    "dashboard": "লাইভ ডেটা",
    "privacy": "গোপনীয়তা এবং সত্য",
    "begin_enrollment": "নথিভুক্তি শুরু করুন",
    "hero_title": "আদমশুমারি 2027: ফোকাসে আমাদের দেশ",
    "hero_subtitle": "প্রতিটি ডেটা একটি ব্যক্তি, একটি পরিবার এবং ভবিষ্যতের প্রতিনিধিত্ব করে।",
    "story_map": "জাতীয় গল্প মানচিত্র",
    "live_sync": "লাইভ সিঙ্ক",
    "click_here": "স্ব-গণনা - এখানে ক্লিক করুন",
    "total_enumerated": "মোট গণনাকৃত",
    "citizens_recorded": "নাগরিক সফলভাবে রেকর্ড করা হয়েছে",
    "target_completion": "লক্ষ্য সমাপ্তি",
    "active_workers": "সক্রিয় মাঠ কর্মী",
    "deployed": "85% মোতায়েন",
    "enum_title": "স্ব-গণনা পোর্টাল",
    "tap_hear": "নির্দেশ শুনতে ট্যাপ করুন",
    "listening": "শুনছি... এখন কথা বলুন",
    "personal_details": "ব্যক্তিগত বিবরণ",
    "full_name": "আপনার পুরো নাম কি?",
    "dob": "জন্ম তারিখ",
    "household_details": "পারিবারিক বিবরণ",
    "address": "আপনি কোথায় বাস করেন?",
    "members": "এখানে কতজন বাস করেন?",
    "review_submit": "পর্যালোচনা এবং জমা দিন",
    "back": "পিছনে",
    "continue": "চালিয়ে যান",
    "submit": "নিরাপদভাবে জমা দিন",
    "name": "নাম",
    "total_members": "মোট সদস্য",
    "speech_welcome": "নমস্কার! আমি আপনার ভয়েস গাইড। চলুন আপনার ব্যক্তিগত তথ্য দিয়ে শুরু করি।",
    "speech_name": "আপনার পুরো নাম কি? কথা বলতে মাইক্রোফোন ট্যাপ করুন।",
    "speech_address": "আপনি কোথায় বাস করেন? ঠিকানা বলতে মাইক ট্যাপ করুন।",
    "speech_back": "এক ধাপ পিছনে যাচ্ছি।",
    "speech_next": "নিখুঁত, চলুন পরবর্তী ধাপে যাই।",
    "speech_submitted": "আপনার কাজ শেষ! আপনার ডেটা নিরাপদে জমা দেওয়া হয়েছে।",
    "success_title": "নথিভুক্তি সফল!",
    "success_message": "আদমশুমারি 2027-এ অংশগ্রহণের জন্য ধন্যবাদ।",
    "go_dashboard": "লাইভ ডেটা ড্যাশবোর্ড দেখুন",
    "gender": "লিঙ্গ",
    "select_gender": "লিঙ্গ নির্বাচন করুন",
    "male": "পুরুষ",
    "female": "মহিলা",
    "transgender": "হিজড়া / অন্যান্য",
    "religion": "ধর্ম",
    "select_religion": "ধর্ম নির্বাচন করুন",
    "hinduism": "হিন্দু ধর্ম",
    "islam": "ইসলাম",
    "christianity": "খ্রিস্টান ধর্ম",
    "sikhism": "শিখ ধর্ম",
    "buddhism": "বৌद्ध ধর্ম",
    "jainism": "জৈন ধর্ম",
    "other": "অন্যান্য",
    "literacy": "সাক্ষরতার অবস্থা",
    "select_literacy": "অবস্থা নির্বাচন করুন",
    "literate": "সাক্ষর",
    "illiterate": "নিরক্ষর",
    "state": "রাজ্য",
    "district": "জেলা",
    "city_town": "শহর / নগর",
    "select_state": "রাজ্য নির্বাচন করুন",
    "select_district": "জেলা নির্বাচন করুন",
    "select_city": "শহর নির্বাচন করুন",
    "enrollment_date": "নথিভুক্তির তারিখ"
  },
  "te": {
    "home": "హోమ్",
    "dashboard": "లైవ్ డేటా",
    "privacy": "గోప్యత",
    "begin_enrollment": "నమోదు ప్రారంభించండి",
    "hero_title": "జనాభా లెక్కలు 2027: మన దేశం",
    "hero_subtitle": "ప్రతి డేటా పాయింట్ ఒక వ్యక్తిని, కుటుంబాన్ని సూచిస్తుంది.",
    "story_map": "జాతీయ కథా పటం",
    "live_sync": "లైవ్ సింక్",
    "click_here": "స్వీయ గణన - ఇక్కడ క్లిక్ చేయండి",
    "total_enumerated": "మొత్తం లెక్కించబడినవి",
    "citizens_recorded": "పౌరులు విజయవంతంగా నమోదు చేయబడ్డారు",
    "target_completion": "లక్ష్యం పూర్తి",
    "active_workers": "క్రియాశీల క్షేత్ర కార్యకర్తలు",
    "deployed": "85% మోహరించారు",
    "enum_title": "స్వీయ-గణన పోర్టల్",
    "tap_hear": "సూచనలు వినడానికి నొక్కండి",
    "listening": "వింటున్నాను... ఇప్పుడు మాట్లాడండి",
    "personal_details": "వ్యక్తిగత వివరాలు",
    "full_name": "మీ పూర్తి పేరు ఏమిటి?",
    "dob": "పుట్టిన తేదీ",
    "household_details": "గృహ వివరాలు",
    "address": "మీరు ఎక్కడ నివసిస్తున్నారు?",
    "members": "ఇక్కడ ఎంత మంది నివసిస్తున్నారు?",
    "review_submit": "సమీక్షించి సమర్పించండి",
    "back": "వెనుకకు",
    "continue": "కొనసాగించండి",
    "submit": "సురక్షితంగా సమర్పించండి",
    "name": "పేరు",
    "total_members": "మొత్తం సభ్యులు",
    "speech_welcome": "నమస్కారం! నేను మీ వాయిస్ గైడ్. మీ సమాచారంతో ప్రారంభిద్దాం.",
    "speech_name": "మీ పూర్తి పేరు ఏమిటి? మాట్లాడటానికి మైక్రోఫోన్ నొక్కండి.",
    "speech_address": "మీరు ఎక్కడ నివసిస్తున్నారు? చిరునామా చెప్పడానికి మైక్ నొక్కండి.",
    "speech_back": "ఒక అడుగు వెనుకకు వెళ్తున్నాను.",
    "speech_next": "పర్ఫెక్ట్, తదుపరి దశకు వెళ్దాం.",
    "speech_submitted": "అంతా పూర్తయింది! మీ డేటా సురక్షితంగా సమర్పించబడింది.",
    "success_title": "నమోదు విజయవంతమైంది!",
    "success_message": "పాల్గొన్నందుకు ధన్యవాదాలు.",
    "go_dashboard": "లైవ్ డేటా డాష్‌బోర్డ్ చూడండి",
    "gender": "లింగం",
    "select_gender": "లింగం ఎంచుకోండి",
    "male": "పురుషుడు",
    "female": "స్త్రీ",
    "transgender": "ట్రాన్స్‌జెండర్ / ఇతర",
    "religion": "మతం",
    "select_religion": "మతం ఎంచుకోండి",
    "hinduism": "హిందూ మతం",
    "islam": "ఇస్లాం",
    "christianity": "క్రైస్తవ మతం",
    "sikhism": "సిక్కు మతం",
    "buddhism": "బౌద్ధ మతం",
    "jainism": "జైన మతం",
    "other": "ఇతర",
    "literacy": "అక్షరాస్యత",
    "select_literacy": "ఎంచుకోండి",
    "literate": "అక్షరాస్యులు",
    "illiterate": "నిరక్షరాస్యులు",
    "state": "రాష్ట్రం",
    "district": "జిల్లా",
    "city_town": "నగరం / పట్టణం",
    "select_state": "రాష్ట్రం ఎంచుకోండి",
    "select_district": "జిల్లా ఎంచుకోండి",
    "select_city": "నగరం ఎంచుకోండి",
    "enrollment_date": "నమోదు తేదీ"
  },
  "ta": {
    "home": "முகப்பு",
    "dashboard": "நேரலை தரவு",
    "privacy": "தனியுரிமை",
    "begin_enrollment": "பதிவை தொடங்குக",
    "hero_title": "மக்கள் தொகை கணக்கெடுப்பு 2027",
    "hero_subtitle": "ஒவ்வொரு தரவும் ஒரு மனிதனை, குடும்பத்தை குறிக்கிறது.",
    "story_map": "தேசிய வரைபடம்",
    "live_sync": "நேரலை ஒத்திசைவு",
    "click_here": "சுய கணக்கெடுப்பு - இங்கே கிளிக் செய்க",
    "total_enumerated": "மொத்தம் கணக்கிடப்பட்டது",
    "citizens_recorded": "குடிமக்கள் பதிவு செய்யப்பட்டுள்ளனர்",
    "target_completion": "இலக்கு நிறைவு",
    "active_workers": "களப் பணியாளர்கள்",
    "deployed": "85% பணியமர்த்தப்பட்டுள்ளனர்",
    "enum_title": "சுய-கணக்கெடுப்பு தளம்",
    "tap_hear": "கேட்க தட்டவும்",
    "listening": "கேட்கிறேன்... இப்போது பேசுங்கள்",
    "personal_details": "தனிப்பட்ட விவரங்கள்",
    "full_name": "உங்கள் முழு பெயர் என்ன?",
    "dob": "பிறந்த தேதி",
    "household_details": "குடும்ப விவரங்கள்",
    "address": "நீங்கள் எங்கே வசிக்கிறீர்கள்?",
    "members": "இங்கு எத்தனை பேர் வசிக்கிறார்கள்?",
    "review_submit": "மதிப்பாய்வு செய்து சமர்ப்பிக்கவும்",
    "back": "பின்னால்",
    "continue": "தொடரவும்",
    "submit": "சமர்ப்பிக்கவும்",
    "name": "பெயர்",
    "total_members": "மொத்த உறுப்பினர்கள்",
    "speech_welcome": "வணக்கம்! நான் உங்கள் குரல் வழிகாட்டி. தொடங்குவோம்.",
    "speech_name": "உங்கள் முழு பெயர் என்ன? பேச மைக்ரோஃபோனை தட்டவும்.",
    "speech_address": "நீங்கள் எங்கே வசிக்கிறீர்கள்? முகவரியை சொல்ல மைக்கை தட்டவும்.",
    "speech_back": "ஒரு படி பின்னால் செல்கிறேன்.",
    "speech_next": "அருமை, அடுத்த படிக்கு செல்வோம்.",
    "speech_submitted": "முடிந்தது! உங்கள் தரவு பாதுகாப்பாக சமர்ப்பிக்கப்பட்டது.",
    "success_title": "பதிவு வெற்றிகரமானது!",
    "success_message": "பங்கேற்றமைக்கு நன்றி.",
    "go_dashboard": "நேரலை தரவு டாஷ்போர்டைக் காண்க",
    "gender": "பாலினம்",
    "select_gender": "பாலினத்தை தேர்ந்தெடுக்கவும்",
    "male": "ஆண்",
    "female": "பெண்",
    "transgender": "திருநங்கை / பிற",
    "religion": "மதம்",
    "select_religion": "மதத்தை தேர்ந்தெடுக்கவும்",
    "hinduism": "இந்து மதம்",
    "islam": "இஸ்லாம்",
    "christianity": "கிறிஸ்தவம்",
    "sikhism": "சீக்கியம்",
    "buddhism": "பௌத்தம்",
    "jainism": "சமணம்",
    "other": "பிற",
    "literacy": "கல்வியறிவு",
    "select_literacy": "தேர்ந்தெடுக்கவும்",
    "literate": "படித்தவர்",
    "illiterate": "படிக்காதவர்",
    "state": "மாநிலம்",
    "district": "மாவட்டம்",
    "city_town": "நகரம் / ஊர்",
    "select_state": "மாநிலத்தை தேர்ந்தெடுக்கவும்",
    "select_district": "மாவட்டத்தை தேர்ந்தெடுக்கவும்",
    "select_city": "நகரத்தை தேர்ந்தெடுக்கவும்",
    "enrollment_date": "பதிவு தேதி"
  },
  "mr": {
    "home": "होम",
    "dashboard": "लाईव्ह डेटा",
    "privacy": "गोपनीयता",
    "begin_enrollment": "नोंदणी सुरू करा",
    "hero_title": "जनगणना २०२७: आपला देश",
    "hero_subtitle": "प्रत्येक डेटा पॉइंट एक व्यक्ती आणि कुटुंबाचे प्रतिनिधित्व करतो.",
    "story_map": "राष्ट्रीय कथा नकाशा",
    "live_sync": "लाईव्ह सिंक",
    "click_here": "स्वयं-गणनेसाठी - येथे क्लिक करा",
    "total_enumerated": "एकूण मोजणी",
    "citizens_recorded": "नागरिकांची यशस्वी नोंद",
    "target_completion": "लक्ष्य पूर्ण",
    "active_workers": "सक्रिय field कामगार",
    "deployed": "८५% तैनात",
    "enum_title": "स्वयं-गणना पोर्टल",
    "tap_hear": "सूचना ऐकण्यासाठी टॅप करा",
    "listening": "ऐकत आहे... आता बोला",
    "personal_details": "वैयक्तिक तपशील",
    "full_name": "तुमचे पूर्ण नाव काय आहे?",
    "dob": "जन्मतारीख",
    "household_details": "कौटुंबिक तपशील",
    "address": "तुम्ही कुठे राहता?",
    "members": "येथे किती लोक राहतात?",
    "review_submit": "पुनरावलोकन आणि सबमिट करा",
    "back": "मागे",
    "continue": "पुढे जा",
    "submit": "सुरक्षितपणे सबमिट करा",
    "name": "नाव",
    "total_members": "एकूण सदस्य",
    "speech_welcome": "नमस्कार! मी तुमचा व्हॉइस मार्गदर्शक आहे. सुरु करूया.",
    "speech_name": "तुमचे पूर्ण नाव काय आहे? बोलण्यासाठी मायक्रोफोन टॅप करा.",
    "speech_address": "तुम्ही कुठे राहता? पत्ता सांगण्यासाठी माईक टॅप करा.",
    "speech_back": "एक पाऊल मागे जात आहे.",
    "speech_next": "उत्तम, पुढच्या टप्प्यावर जाऊया.",
    "speech_submitted": "तुमचे काम झाले! तुमचा डेटा सुरक्षितपणे सबमिट झाला आहे.",
    "success_title": "नोंदणी यशस्वी!",
    "success_message": "सहभागाबद्दल धन्यवाद.",
    "go_dashboard": "लाईव्ह डेटा डॅशबोर्ड पहा",
    "gender": "लिंग",
    "select_gender": "लिंग निवडा",
    "male": "पुरुष",
    "female": "स्त्री",
    "transgender": "तृतीयपंथी / इतर",
    "religion": "धर्म",
    "select_religion": "धर्म निवडा",
    "hinduism": "हिंदू",
    "islam": "इस्लाम",
    "christianity": "ख्रिश्चन",
    "sikhism": "शीख",
    "buddhism": "बौद्ध",
    "jainism": "जैन",
    "other": "इतर",
    "literacy": "साक्षरता",
    "select_literacy": "निवडा",
    "literate": "साक्षर",
    "illiterate": "निरक्षर",
    "state": "राज्य",
    "district": "जिल्हा",
    "city_town": "शहर",
    "select_state": "राज्य निवडा",
    "select_district": "जिल्हा निवडा",
    "select_city": "शहर निवडा",
    "enrollment_date": "नोंदणी तारीख"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [lang, setLang] = useState<Language>("en");

  const t = (key: string) => {
    return translations[lang]?.[key] || translations["en"]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};
